---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resources-cleanup-policy.neo9.io
spec:
  scope: Cluster
  group: neo9.io
  names:
    kind: ResourceCleanupPolicy
    listKind: ResourcesCleanupPolicy
    plural: resources-cleanup-policy
    singular: resources-cleanup-operator
    shortNames:
      - rcp
      - rcps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Resources Cleanup Policy. Delete resources based on custom policy
          type: object
          properties:
            spec:
              type: object
              properties:
                kind:
                  description: Resource type to be monitored
                  type: string
                namespaces:
                  description: List of namespace to be monitored
                  type: array
                  items:
                    type: string
                excludeNamespaces:
                  description: List of namespace to be excluded from cleaning
                  type: array
                  items:
                    type: string
                interval:
                  description: >-
                    Delay between every scan to find resource to cleanup
                  type: string
                history:
                  type: object
                  properties:
                    age:
                      description: >-
                        Age of resource to target
                      type: string
                      default: "0s"
                    toKeep:
                      description: >-
                        Number of most recent resource to keep
                      type: integer
                      default: -1
                selector:
                  description: >-
                    List of labels to match resources containing only those labels
                  type: object
                  additionalProperties:
                    type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
