# Default values for eck-managed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: eck

elasticsearch:
  enabled: true
  version: 7.16.2
  replicaCount: 2
  labels: {}  
  annotations: {}
  service:
    annotations: {}
    labels: {}
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 2
      memory: 8Gi
  pod:
    elasticsearch:
      env:
        - name: ES_JAVA_OPTS
          value: -Xms4g -Xmx4g
  volumeClaim:
    spec:
      storageClassName: gcp-sc-retain-wait-ssd
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  config:
    node.master: true
    node.data: true
    node.ingest: true
    node.store.allow_mmap: false
    xpack.security.authc:
      anonymous:
        username: anonymous
        roles: superuser
        authz_exception: false
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  scheduling:
    # -- Max difference of number of pods between nodes using topologySpreadConstraints
    maxSkewPerNode: 1

################################################################################
# ES exporter configuration.
################################################################################

es-exporter:
  enabled: true
  es:
    uri: http://catalogue-elasticsearch-es-default:9200

################################################################################
# Kibana configuration.
################################################################################

kibana:
  enabled: true

  # Define the Kibana version.
  version: 7.16.2

  # Configure pod resources.
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
    limits:
      memory: 1Gi
      cpu: 1

  labels: {}
  annotations: {}
  # Define a node selector.
  #
  affinity: {}
  nodeSelector: {}
    # type: main
  tolerations: []
  topologySpreadConstraints: []
  scheduling:
    # -- Max difference of number of pods between nodes using topologySpreadConstraints
    maxSkewPerNode: 1

  # By default, this property is empty. When empty, the chart will fetch the value specified into
  # `.Values.elasticsearch.fullnameOverride` automatically.
  #
  # elasticsearchRef:

  # Define the number of replicas.
  replicaCount: 1

  # Configure the HTTP service.
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      metadata:
        annotations: {}
        labels: {}
