apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "rabbitmq-managed.fullname" . }}
  labels:
    {{- include "rabbitmq-managed.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cluster.replicaCount }}
  {{- if .Values.cluster.image }}
  image: {{ .Values.cluster.image }}
  {{- end }}
{{- if or .Values.cluster.resources.limits .Values.cluster.resources.requests }}
  resources:
  {{- if .Values.cluster.resources.limits }}
    limits:
    {{- toYaml .Values.cluster.resources.limits | nindent 6 }}
  {{- end }}
  {{- if .Values.cluster.resources.requests }}
    requests:
    {{- toYaml .Values.cluster.resources.requests | nindent 6 }}
  {{- end }}
{{- end }}
  persistence:
    storage: {{ .Values.cluster.storage.size }}
    {{- if .Values.cluster.storage.storageClass }}
    storageClassName: {{ .Values.cluster.storage.storageClass }}
    {{- end }}
  {{- if .Values.cluster.rabbitmqConf }}
  rabbitmq:
    {{- toYaml .Values.cluster.rabbitmqConf | nindent 4 }}
  {{- end }}
  {{- if .Values.affinity }}
  affinity: {{ toYaml .Values.affinity | nindent 4 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations: {{ toYaml .Values.tolerations | nindent 4 }}
  {{- end }}
  override:
    {{- if not .Values.cluster.override }}
    statefulSet:
      metadata:
        labels:
        {{ toYaml .Values.cluster.statefulSetLabels | indent 2 }}
      spec:
        template:
          metadata:
            labels:
            {{ toYaml .Values.cluster.podLabels | indent 2 }}
          spec:
            {{- if .Values.cluster.overrideContainers }}
            containers: {{- toYaml .Values.cluster.overrideContainers | nindent 12 }}
            {{- else }}
            containers: []
            {{- end }}
            {{- if .Values.nodeSelector }}
            nodeSelector: {{ toYaml .Values.nodeSelector | nindent 14 }}
            {{- end }}
            topologySpreadConstraints:
            {{- if .Values.scheduling.maxSkewPerNode }}
            - maxSkew: {{ .Values.scheduling.maxSkewPerNode }}
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule 
              labelSelector:
                matchLabels:
                  {{- include "rabbitmq-managed.selectorLabels" . | nindent 18 }}
            {{- if .Values.topologySpreadConstraints }}
            {{- toYaml .Values.topologySpreadConstraints | nindent 12 }}
            {{- end }}
            {{- end }}
    {{- else }}
    {{- toYaml .Values.cluster.override | nindent 4 }}
    {{- end }}
  {{- with .Values.cluster.extraSpec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
