{{- range $user := .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq-managed.fullname" $ }}-user-{{ $user.name }}
  labels:
    {{- include "rabbitmq-managed.labels" $ | nindent 4 }}
stringData: 
  username: {{ $user.name }}
{{- end }}