{{- range $user := .Values.users }}
{{- if not (($user.importCredentialsSecret).name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq-managed.fullname" $ }}-user-{{ $user.name }}-source
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  username: {{ $user.name }}
{{- end }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: {{ include "rabbitmq-managed.fullname" $ }}-user-{{ $user.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rabbitmq-managed.labels" $ | nindent 4 }}
spec:
  {{- if $user.tags }}
  tags: {{ toYaml $user.tags | nindent 2 }}
  {{- end }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq-managed.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
  {{- if (($user.importCredentialsSecret).name) }}
  importCredentialsSecret:
    name: {{ (($user.importCredentialsSecret).name) }}
  {{- else }}
  importCredentialsSecret:
    name: {{ include "rabbitmq-managed.fullname" $ }}-user-{{ $user.name }}-source
  {{- end }}
{{- end }}
