{{- if .Values.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "eck-managed.fullname" . }}-kibana
spec:
  version: {{ .Values.kibana.version }}
  config:
    {{- toYaml .Values.kibana.config | nindent 6 }}
  podTemplate:
    metadata:
      labels: {{ toYaml .Values.kibana.labels | nindent 8 }}
      annotations: {{ toYaml .Values.kibana.annotations | nindent 8 }}
    spec:
      {{- if .Values.kibana.affinity }}
      affinity: {{ toYaml .Values.kibana.affinity | nindent 8 }}
      {{- else if .Values.elasticsearch.affinity }}
      affinity: {{ toYaml .Values.elasticsearch.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.kibana.nodeSelector }}
      nodeSelector: {{ toYaml .Values.kibana.nodeSelector | nindent 8 }}
      {{- else if .Values.elasticsearch.nodeSelector }}
      nodeSelector: {{ toYaml .Values.elasticsearch.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.kibana.tolerations}}
      tolerations: {{ toYaml .Values.kibana.tolerations | nindent 8 }}
      {{- else if .Values.elasticsearch.tolerations}}
      tolerations: {{ toYaml .Values.elasticsearch.tolerations | nindent 8 }}
      {{- end }}
      {{- if or .Values.kibana.topologySpreadConstraints .Values.kibana.scheduling.maxSkewPerNode }}
      topologySpreadConstraints: 
      {{- if .Values.kibana.scheduling.maxSkewPerNode }}
      - maxSkew: {{ .Values.kibana.scheduling.maxSkewPerNode }}
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule 
        labelSelector:
          matchLabels:
            {{- include "eck-managed.selectorLabels" . | nindent 12 }}
      {{- if .Values.kibana.topologySpreadConstraints }}
      {{- toYaml .Values.kibana.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- else if or .Values.elasticsearch.topologySpreadConstraints .Values.elasticsearch.maxSkewPerNode }}
      topologySpreadConstraints: 
      {{- if .Values.elasticsearch.scheduling.maxSkewPerNode }}
      - maxSkew: {{ .Values.elasticsearch.scheduling.maxSkewPerNode }}
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule 
        labelSelector:
          matchLabels:
            {{- include "eck-managed.selectorLabels" . | nindent 12 }}
      {{- if .Values.elasticsearch.topologySpreadConstraints }}
      {{- toYaml .Values.elasticsearch.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
      - name: kibana
        resources: {{- toYaml ((.Values.kibana).resources | default dict) | nindent 10 }}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
  http: {{- toYaml ((.Values.kibana).http | default dict) | nindent 4 }}
  elasticsearchRef:
    name: {{ (.Values.kibana).elasticsearchRef | default (printf "%s-%s" (include "eck-managed.fullname" .) "elasticsearch") }}
  count: {{ (.Values.kibana).replicaCount | default 1 }}
{{- end }}
