nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className:
  annotations: {}
  labels: {}
  # -- Define the hostname to use.
  host: "example.test"
  tls:
    # -- Enable TLS, with a default secret reference
    enabled: true
    # -- Specify an existing secret if not automatically provisionned
    customSecretName: ""

cluster:
  # -- Configure number of rabbitmq replicas (should be an odd numbers)
  replicaCount: 3
  # -- Specify an image to use if different from operator default
  image: ""
  # -- If using default memory_high_watermark, consider memory limits being ~3 times the requests
  resources:
    # -- Define rabbitmq cluster container limits.
    limits: {}
      # cpu: "2"
      # memory: 2G
    # -- Define rabbitmq cluster container requests.
    requests: {}
      # cpu: "1"
      # memory: 2G
  # -- VolumeClaimTemplate can't be edited on a statefulset, those values only permit instance configuration at creation
  storage:
    # -- If edited it will recreate the rabbitmq statefulset
    size: 10Gi
    # -- Can only be set on creation, later edit require whole cluster replacement or pvc/data migration
    storageClass: ""
  # -- Inject rabbitmq conf, which are under RabbitmqCluster.spec.rabbitmq
  rabbitmqConf: {}
  # -- Set value to override the templated statefulset by the operator
  override: {}
  # -- Inject values directly into .spec of RabbitmqCluster manifests
  extraSpec: {}


# -- The default vhost (`/`) is automatically created
vhosts: []

# -- Define the list of users, assigned vhosts and corresponding permissions
users: []
  # - name: admin
  #   tags: ["administrator"] # (optional)
  #   importCredentialsSecret: # This will simply import credentials into `{release-name}-user-{user}-user-credentials` (optional)
  #     name: my-secret-name # (optional)
  #   permissions:
  #     - vhost: custom-vhost
  #       write: ".*"     # (optional)
  #       configure: ".*" # (optional)
  #       read: ".*"      # (optional)

  # - name: admin
  #   tags: ["administrator"]
  #   permissions:
  #     - vhost: /

  # - name: catalogue-cms-api
  #   permissions:
  #     - vhost: catalogue

# -- Create rabbitmq policy to apply automatically
policies: []
  # - name: "ha"
  #   vhosts: "catalogue"
  #   pattern: ".*"
  #   applyTo: "all"
  #   definition:
  #     ha-mode: all
  #     ha-sync-mode: automatic
affinity: []
tolerations: []
nodeSelector: []
topologySpreadConstraints: 
# - maxSkew: 1
#   topologyKey: kubernetes.io/hostname
#   whenUnsatisfiable: DoNotSchedule
scheduling:
  # -- Max difference of number of pods between nodes using topologySpreadConstraints
  maxSkewPerNode: 1