apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: build-tool
spec:
  description: >-
    This task can be used to run npm goals on a project.

    This task can be used to run npm goals on a project
    where package.json is present and has some pre-defined
    npm scripts.
  workspaces:
    - name: source
  params:
    - name: PATH_CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
    - name: ARGS
      type: string
      default: ""
      description: The npm goals you want to run.
    - name: IMAGE
      type: string
      default: "docker.io/library/node:12-alpine@sha256:12048cdfd75d944df35f3144132d9bdeee78015fbd6df765edad1be46599b110"
      description: The node image you want to use.
    - name: COMMAND
      type: string
      default: "npm"
  steps:
    - name: npm-run
      image: $(params.IMAGE)
      resources:
        requests:
          memory: 300m
          cpu: 300m
        limits:
          memory: 1Gi
          cpu: 800m
      script: |
        #!/bin/sh
        $(params.COMMAND) $(params.ARGS)
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      env:
        - name: CI
          value: "true"
        - name: NODE_OPTIONS
          value: "--max_old_space_size=750"
