{{- if (index .Values "external-secrets" "enabled") -}}
{{- if (index .Values "external-secrets" "rabbitmqSecretStore" "enabled") -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-rabbitmq-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount: 
          {{- toYaml (index $.Values "external-secrets").rabbitmqSecretStore.serviceAccount | nindent 10 }}
      remoteNamespace: {{ (index $.Values "external-secrets").rabbitmqNamespace | default ($.Release.Namespace) }}
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: {{ ($.Release.Namespace) }}
          type: ConfigMap
        url: https://kubernetes.default.svc
{{- end }}
{{- end }}