{{- if .Values.catalogue.configMap }}
{{- range .Values.catalogue.configMap }}
{{- $rangeItem := . -}}
{{- with $ }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalogue.fullname" . }}-{{ $rangeItem.name }}
  labels:
    {{- include "catalogue.labels" . | nindent 4 }}
data:
  {{ toYaml $rangeItem.content | indent 2 | trim }}
{{- end }}
{{- end }}
{{- end }}